export const ON_LOGIN = 'ON_LOGIN';
export const ON_LOGIN_SUCCESS = 'ON_LOGIN_SUCCESS';
export const ON_LOGIN_FAIL = 'ON_LOGIN_FAIL';

export const ON_SIGNUP = 'ON_SIGNUP';
export const ON_SIGNUP_SUCCESS = 'ON_SIGNUP_SUCCESS';
export const ON_SIGNUP_FAIL = 'ON_SIGNUP_FAIL';

export const ON_LOGIN_FORM_TYPE = 'ON_LOGIN_FORM_TYPE';
export const ON_SIGNUP_FORM_TYPE = 'ON_SIGNUP_FORM_TYPE';

export const LOGOUT = 'LOGOUT';

export const REDIRECT = 'REDIRECT';

export const ON_BOOKMARK = 'ON_BOOKMARK';
export const ON_BOOKMARK_SUCCESS = 'ON_BOOKMARK_SUCCESS';
export const ON_BOOKMARK_FAIL = 'ON_BOOKMARK_FAIL';

export const ON_BOOKMARK_SEARCH = 'ON_BOOKMARK_SEARCH';
export const ON_BOOKMARK_SEARCH_SUCCESS = 'ON_BOOKMARK_SEARCH_SUCCESS';
export const ON_BOOKMARK_SEARCH_FAIL = 'ON_BOOKMARK_SEARCH_FAIL';

export const ON_BOOKMARK_EDIT = 'ON_BOOKMARK_EDIT';
